name: action-genai-pull-request-descriptor
description: Generate a pull request description based on the changes in the codebase
inputs:
  base:
    description: The base branch of the pull request
    required: false
  gitmojis:
    description: Whether to use gitmojis in the pull request description
    required: false
    default: true
  instructions:
    description: Instructions for the code reviewer
    required: false
  excluded:
    description: Excluded paths from diff
    required: false
  github_token:
    description: "GitHub token with `models: read` permission at least
      (https://microsoft.github.io/genaiscript/reference/github-actions/#github\
      -models-permissions)."
    required: true
  github_issue:
    description: GitHub pull request number to use when generating comments
      (https://microsoft.github.io/genaiscript/reference/scripts/github/).
  debug:
    description: Enable debug logging
      (https://microsoft.github.io/genaiscript/reference/scripts/logging/).
    required: false
branding:
  color: yellow
  icon: hard-drive
runs:
  using: docker
  image: Dockerfile
outputs:
  text:
    description: The generated text output.
