name: action-genai-pull-request-descriptor
description: Action
inputs:
  instructions:
    description: "Additional prompting instructions"
  gitmojis:
    description: "Whether to use gitmojis in the pull request description"
    default: true
  github_token:
    description: "GitHub token with `models: read` permission at least
      (https://microsoft.github.io/genaiscript/reference/github-actions/#github\
      -models-permissions)."
  github_issue:
    description: "The issue number to associate with the pull request."
  debug:
    description: Enable debug logging
      (https://microsoft.github.io/genaiscript/reference/scripts/logging/).
    required: false
branding:
  color: yellow
  icon: hard-drive
runs:
  using: docker
  image: Dockerfile
