name: GenAI Pull Request Descriptor
on:
    workflow_dispatch:
        inputs:
            issue_number:
                type: number
                description: "The issue number to associate with the pull request."
                required: true
    pull_request:
        types: [opened, reopened, ready_for_review]
permissions:
    contents: read
    pull-requests: write
    models: read
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.issue_number || github.event.pull_request.number }}
    cancel-in-progress: true
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pelikhan/action-genai-pull-request-descriptor@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_issue: ${{ github.event.inputs.issue_number || github.event.pull_request.number }}